
version: "3"
services:
  database.postgres:
    image: sameersbn/postgresql:latest
    container_name: postgres-miniflux
    environment:
      - DB_NAME=miniflux2
      - PG_PASSWORD=miniflux # please change the password
    volumes:
      - ~/postgres/data/:/var/lib/postgresql/ # persist postgres data to ~/postgres/data/ on the host
    restart: always
  service.rss:
    image: fengkx/miniflux:amd64-latest
    container_name: miniflux
    ports:
      - 2507:8080
    environment: #see all env at https://miniflux.app/docs/configuration.html
      - DEBUG
      - WORKER_POOL_SIZE=5
      - POLLING_FREQUENCY=60
      - BATCH_SIZE=10
      - RUN_MIGRATIONS=1
      - BASE_URL=http://localhost/ #please change to your domain
      #please change the password in DATABASE_URL the same as PG_PASSWORD above
      - DATABASE_URL= host=database.postgres user=postgres password=miniflux dbname=miniflux2 sslmode=disable
      - DATABASE_MAX_CONNS=20
      - DATABASE_MIN_CONNS=1
      - ARCHIVE_READ_DAYS=60
      - PORT=8080
      - CREATE_ADMIN=1
      - ADMIN_USERNAME=admin
      - ADMIN_PASSWORD=password #please change the password
      - HTTP_CLIENT_TIMEOUT=20
    restart: always
    command: sh -c /usr/bin/miniflux

  service.mercury: # set Mercury Parser API endpoint to `http://service.mercury:3000/parser` on miniflux seeting
    image: wangqiru/mercury-parser-api:latest
    container_name: mercury-miniflux
    expose:
      - 3000
    restart: always
